services:
  shell:
    build:
      context: .
      target: shell
    ports:
      - "8080:80"
    environment:
      PEOPLE_REMOTE_URL: http://localhost:8080/remotes/people/remoteEntry.js
      DELIVERY_REMOTE_URL: http://localhost:8080/remotes/delivery/remoteEntry.js

  people:
    build:
      context: .
      target: people
    ports:
      - "8081:80"

  delivery:
    build:
      context: .
      target: delivery
    ports:
      - "8082:80"
