server {
    listen 80;
    root /usr/share/nginx/html;

    location /people/ {
        proxy_pass http://people:80/;
    }

    location /delivery/ {
        proxy_pass http://delivery:80/;
    }

    location = /config.json {
        add_header Cache-Control "no-store";
    }

    location / {
        try_files $uri /index.html;
    }
}